Repository JDimproved/JDim, pull requests merged in 2019-08, with the labels that each got.

#100 add CPPFLAGS, CXXFLAGS and LDFLAGS for test
  jdim.desktop
  test/Makefile.in
Labels: test

#105 Fix #101 Remove subversion support
  Makefile.am
  configure.ac
  src/environment.cpp
  src/jdversion.h
Labels: feature

#106 Fix #102: Update application icon installation
  Makefile.am
  jd.png
  jdim.desktop
  jdim.png
Labels: refactoring

#107 Fix #103: Add jdim.metainfo.xml
  Makefile.am
  jdim.metainfo.xml
Labels: document

#108 Fix #104: Implement XDG Base Directory support for cache
  .travis.yml
  INSTALL
  README.md
  configure.ac
  docs/manual/2019.md
  docs/manual/asciiart.md
  docs/manual/backup.md
  docs/manual/make.md
  docs/manual/skin.md
  docs/manual/sound.md
  docs/manual/start.md
  docs/manual/usrcmd.md
  src/cache.cpp
Labels: feature

#115 Fix markdown format for the table of cache directory priority
  docs/manual/start.md
Labels: document

#111 Fix #109: Remove cache root config providing compatible with old version
  src/config/configitems.cpp
  src/config/configitems.h
  src/config/defaultconf.h
Labels: feature

#112 Fix configure args info to include "without" and "disable" options
  src/environment.cpp
Labels: bug

#113 Add smooth scroll event to enable mouse wheel on GTK3
  README.md
  docs/manual/start.md
  src/article/drawareabase.cpp
  src/article/drawareabase.h
  src/skeleton/dragtreeview.cpp
  src/skeleton/dragtreeview.h
Labels: feature, gtk3

#114 Implement tab switch by mouse wheel for GTK3
  README.md
  docs/manual/2019.md
  docs/manual/start.md
  src/skeleton/dragnote.cpp
  src/skeleton/dragnote.h
  src/skeleton/tablabel.cpp
Labels: feature, gtk3

#117 Improve tab switch by mouse wheel for image view
  docs/manual/2019.md
  src/article/drawareabase.h
  src/image/imageadmin.cpp
  src/image/imageadmin.h
  src/image/imageviewicon.cpp
  src/image/imageviewicon.h
  src/skeleton/dragnote.h
  src/skeleton/dragtreeview.h
Labels: feature, gtk3

#118 Add snapcraft.yaml
  docs/manual/2019.md
  snap/snapcraft.yaml
Labels: snap
