Repository JDimproved/JDim, pull requests merged in 2019-03, with the labels that each got.

#42 Fix variable type for assigning from std::string::find()
  src/control/controlutil.cpp
Labels: bug

#43 Replace JDLIB::hash_set_thread with std::unordered_set
  src/bbslist/bbslistviewbase.cpp
  src/bbslist/bbslistviewbase.h
  src/board/boardviewlog.cpp
  src/board/boardviewlog.h
  src/board/boardviewsidebar.cpp
  src/board/boardviewsidebar.h
  src/jdlib/Makefile.am
  src/jdlib/hash_set.cpp
  src/jdlib/hash_set.h
Labels: performance

#44 Add MATE and Cinnamon to ENVIRONMENT::get_wm()
  src/environment.cpp
  src/environment.h
  src/jdversion.h
  src/skeleton/window.cpp
Labels: feature

#47 Avoid crash on extraction
  src/jdlib/jdregex.cpp
Labels: bug

#49 font.cpp内のmallocをnewに置き換える
  src/article/font.cpp
Labels: bug

#51 Fix oniguruma detection for configure script
  configure.ac
Labels: bug

#52 Fix runtime warning for opening a thread since GTK+ 3.20
  src/article/drawareabase.cpp
  src/jdversion.h
Labels: bug, gtk3

#54 Add downloading dat from old URL
  src/dbtree/nodetree2ch.cpp
Labels: feature

#55 Fix #40: Make --with-gthread deprecated
  INSTALL
  configure.ac
  src/jdversion.h
Labels: feature

#56 Sanitize numeric character reference
  src/jdlib/miscutil.cpp
Labels: bug

#57 Update function parameters for MISC::asc()
  src/jdlib/jdregex.cpp
  src/jdlib/jdregex.h
  src/jdlib/miscutil.cpp
  src/jdlib/miscutil.h
Labels: refactoring

#58 Fix released-event misfire for GtkGestureMultiPress
  src/article/drawareabase.cpp
Labels: bug, gtk3

#61 Use std::unordered_set instead of std::vector for res information
  src/article/preference.cpp
  src/dbtree/articlebase.cpp
  src/dbtree/articlebase.h
  src/dbtree/interface.cpp
  src/dbtree/interface.h
  src/dbtree/nodetreebase.cpp
  src/dbtree/nodetreebase.h
  src/jdlib/constptr.h
Labels: feature

#62 #53 の修正
  src/article/articleview.cpp
  src/article/articleview.h
  src/article/drawareabase.cpp
  src/article/layouttree.cpp
  src/article/layouttree.h
  src/board/preference.cpp
  src/config/aboutconfig.cpp
  src/config/configitems.cpp
  src/config/configitems.h
  src/config/defaultconf.h
  src/config/globalconf.cpp
  src/config/globalconf.h
  src/dbtree/articlebase.cpp
  src/dbtree/board2chcompati.cpp
  src/dbtree/boardbase.cpp
  src/dbtree/boardjbbs.cpp
  src/dbtree/boardmachi.cpp
  src/dbtree/node.h
  src/dbtree/nodetreebase.cpp
  src/dbtree/nodetreebase.h
  src/global.h
  src/skeleton/toolbar.cpp
  src/skeleton/view.cpp
  src/skeleton/view.h
Labels: feature

#63 Use range-based for instead of MISC::count_chr()
  src/jdlib/miscutil.cpp
  src/jdlib/miscutil.h
  src/message/messageviewbase.cpp
Labels: refactoring

#64 Tweak config dialog layout for GTK+3
  src/control/mousekeypref.cpp
  src/linkfilterpref.cpp
  src/usrcmdpref.cpp
Labels: bug, gtk3

#65 Fix #60: Change default thread title search site (ff5ch.syoboi.jp)
  src/config/defaultconf.h
  src/jdversion.h
Labels: feature
