Repository JDimproved/JDim, pull requests merged in 2020-02, with the labels that each got.

#177 Update requirements for dependencies (gtkmm >= 2.24)
  INSTALL
  README.md
  configure.ac
  docs/manual/make.md
Labels: feature

#178 Remove deprecated --with-sessionlib=gnomeui option
  INSTALL
  configure.ac
  docs/manual/make.md
  src/Makefile.am
  src/main.cpp
  test/Makefile.in
Labels: feature

#179 Replace dynamic allocation with local variable for struct utsname
  docs/manual/2020.md
  src/environment.cpp
Labels: refactoring

#181 CONTROL::get_keyconfig use snprintf and set copying buffer size corre…
  src/control/controlutil.cpp
Labels: bug

#184 HEAP::heap_alloc(): adjust alignment
  src/cssmanager.cpp
  src/dbtree/nodetreebase.cpp
  src/jdlib/heap.cpp
  src/jdlib/heap.h
Labels: bug

#185 Fix number of bytes for strncpy argument of Css_Manager::create_textnode()
  src/cssmanager.cpp
Labels: bug

#186 Replace char buffer with std::string for DBTREE::NodeTreeJBBS
  src/dbtree/nodetreejbbs.cpp
  src/dbtree/nodetreejbbs.h
Labels: refactoring

#187 Fix a -Wstringop-overflow compiler warning in create_trip_newtype()
  docs/manual/2020.md
  src/jdlib/misctrip.cpp
Labels: bug

#188 Fix buffer overrun for MISC::is_url_scheme_impl() test
  test/gtest_jdlib_miscutil.cpp
Labels: test

#189 Remove zlib client codes for version < 1.2.0
  src/jdlib/loader.cpp
  src/jdlib/loader.h
Labels: feature

#190 Replace char buffer with std::string for DBTREE::NodeTreeMachi
  docs/manual/2020.md
  src/dbtree/nodetreemachi.cpp
  src/dbtree/nodetreemachi.h
Labels: refactoring

#191 Fix not setting result to the out parameter of NodeTreeMachi::raw2dat()
  src/dbtree/nodetreemachi.cpp
Labels: bug

#192 Improve JDLIB::HEAP to return pointer aligned by specified type
  INSTALL
  docs/manual/make.md
  src/article/layouttree.cpp
  src/cssmanager.cpp
  src/dbtree/nodetreebase.cpp
  src/jdlib/heap.cpp
  src/jdlib/heap.h
Labels: performance

#193 Remove unused NodeTreeBase::get_raw_res_str()
  src/dbtree/articlebase.cpp
  src/dbtree/articlebase.h
  src/dbtree/nodetreebase.cpp
  src/dbtree/nodetreebase.h
Labels: refactoring

#194 Remove legacy gtk2 codes for less than version 2.24
  docs/manual/2020.md
  src/control/keysyms.h
  src/skeleton/aamenu.cpp
  src/skeleton/editview.cpp
  src/skeleton/entry.cpp
  src/skeleton/msgdiag.cpp
  src/skeleton/selectitempref.cpp
  src/skeleton/tabnote.cpp
  src/skeleton/view.cpp
  src/skeleton/window.cpp
Labels: feature
