Repository JDimproved/JDim, pull requests merged in 2020-01, with the labels that each got.

#163 Add a description for undocumented operation to the manual
  docs/manual/operation.md
Labels: document

#164 Update year to 2020
  README.md
  docs/index.md
  docs/manual/2019.md
  docs/manual/2020.md
  docs/manual/about.md
  docs/manual/history.md
  src/jdversion.h
Labels: document

#166 Replace char buffer with std::string for MISC::Iconv()
  src/jdlib/miscutil.cpp
Labels: refactoring

#165 Update snapcraft grade to stable
  README.md
  docs/manual/2020.md
  docs/manual/start.md
  snap/snapcraft.yaml
  test/Makefile.in
Labels: document, snap

#167 Replace char buffer with std::string for DBTREE::BoardBase
  src/dbtree/boardbase.cpp
  src/dbtree/boardbase.h
Labels: refactoring

#168 Refactor ARTICLE::DrawAreaBase
  src/article/drawareabase.cpp
Labels: refactoring

#172 Set gtkmm3 as default for configure script
  INSTALL
  README.md
  configure.ac
  docs/manual/make.md
Labels: feature, gtk3

#173 Set std::thread as default for configure script
  INSTALL
  configure.ac
  docs/manual/make.md
Labels: feature

#174 Migrate snap package from legacy helper to gnome extension
  docs/manual/2020.md
  snap/snapcraft.yaml
Labels: refactoring, snap

#176 MISC::remove_space: handle the case str consists of just spaces
  src/jdlib/miscutil.cpp
Labels: bug
