Repository JDimproved/JDim, pull requests merged in 2020-03, with the labels that each got.

#195 Separate mail font
  src/article/drawareabase.cpp
  src/article/drawareabase.h
  src/config/configitems.cpp
  src/config/defaultconf.h
  src/core.cpp
  src/core.h
  src/dbtree/nodetreebase.cpp
  src/dbtree/nodetreebase.h
  src/fontcolorpref.cpp
  src/fontid.h
  src/menuslots.cpp
  src/setupwizard.cpp
  src/setupwizard.h
Labels: feature

#196 Root: Fix parsing bbsmenu for 2ch.sc and next2ch.net
  src/dbtree/root.cpp
Labels: bug

#197 MISC::asc: Fix crash when searching title on Machi BBS
  src/jdlib/miscutil.cpp
Labels: bug

#199 Fix out-of-range for JDLIB::Regex::exec()
  docs/manual/2020.md
  src/jdlib/miscutil.cpp
  test/gtest_jdlib_miscutil.cpp
Labels: bug, test

#201 Add autoconf-archive to build requirement
  INSTALL
  docs/manual/make.md
Labels: document

#202 Fix thread view popup window scrolling for GTK3
  src/article/drawareabase.cpp
Labels: bug, gtk3

#203 Implement mouse gesture wheel for GTK3
  src/article/articleviewbase.cpp
  src/bbslist/bbslistviewbase.cpp
  src/board/boardviewbase.cpp
  src/control/control.cpp
  src/image/imageviewbase.cpp
Labels: feature, gtk3

#204 Reduce memory usage for font width caches
  src/article/font.cpp
Labels: performance

#206 layout_one_text_node: reset br_size after writing characters
  src/article/drawareabase.cpp
Labels: bug

#205 Update manual
  README.md
  docs/manual/2020.md
  docs/manual/skin.md
  docs/manual/start.md
Labels: document

#208 DrawAreaBase: Fix member initialization
  src/article/drawareabase.cpp
  src/article/drawareabase.h
  src/article/scrollinfo.h
Labels: bug, help wanted

#210 Replace XML::DomList with std::list<XML::Dom*>
  src/aamanager.cpp
  src/bbslist/bbslistviewbase.cpp
  src/dbtree/root.cpp
  src/history/historymanager.cpp
  src/linkfiltermanager.cpp
  src/usrcmdmanager.cpp
  src/xml/Makefile.am
  src/xml/document.cpp
  src/xml/dom.cpp
  src/xml/dom.h
  src/xml/domlist.cpp
  src/xml/domlist.h
Labels: refactoring

#213 Fix wordings for about:config favorite category to directory
  src/config/aboutconfig.cpp
  src/config/configitems.cpp
  src/config/configitems.h
  src/config/defaultconf.h
  src/config/globalconf.cpp
  src/config/globalconf.h
Labels: document

#211 Fix compiler warning -Wformat-truncation= for MISC::timettostr()
  src/jdlib/misctime.cpp
  test/gtest_jdlib_misctime.cpp
Labels: bug

#212 Replace char buffer with std::string for DBTREE::NodeTreeBase [1/2]
  docs/manual/2020.md
  src/dbtree/nodetreebase.cpp
  src/dbtree/nodetreebase.h
Labels: refactoring

#215 Implement high reference extraction
  src/article/articleadmin.cpp
  src/article/articleviewbase.cpp
  src/article/articleviewbase.h
  src/article/articleviewetc.cpp
  src/article/articleviewetc.h
  src/core.cpp
  src/dbtree/articlebase.cpp
  src/dbtree/articlebase.h
  src/dbtree/nodetreebase.cpp
  src/dbtree/nodetreebase.h
  src/sign.h
  src/viewfactory.cpp
  src/viewfactory.h
Labels: feature

#216 Iconv::convert: handle emoji subdivision flags sequence
  src/jdlib/jdiconv.cpp
Labels: bug

#217 snap: Remove dbus slot from snapcraft.yaml
  snap/snapcraft.yaml
Labels: snap

#218 Fix thread view font configuration for GTK2
  src/article/drawareabase.cpp
Labels: bug

#219 ArticleViewMain: Fix member initialization
  src/article/articleview.cpp
  src/article/articleview.h
Labels: bug

#220 Replace char buffer with std::string for DBTREE::NodeTreeBase [2/2]
  src/dbtree/nodetreebase.cpp
  src/dbtree/nodetreebase.h
Labels: refactoring

#221 Refactor XML::Dom
  docs/manual/2020.md
  src/xml/dom.cpp
  src/xml/dom.h
  test/gtest_xml_dom.cpp
Labels: refactoring, test

#222 ArticleViewBase: Fix member initialization
  src/article/articleviewbase.cpp
  src/article/articleviewbase.h
Labels: bug

#223 Replace char buffer with std::string for CACHE::jdcopy()
  src/cache.cpp
Labels: refactoring

#224 Refactor XML::Dom part2
  docs/manual/2020.md
  src/xml/dom.cpp
  src/xml/dom.h
Labels: refactoring
