Repository JDimproved/JDim, pull requests merged in 2023-01, with the labels that each got.

#1087 Update year to 2023
  README.md
  docs/index.md
  docs/manual/2022.md
  docs/manual/2023.md
  docs/manual/about.md
  docs/manual/history.md
  src/jdversion.h
Labels: document

#1088 Release 0.9.0
  docs/index.md
  docs/manual/2023.md
  docs/manual/link-20230107.md
  jdim.metainfo.xml
  meson.build
  src/jdversion.h
Labels: document

#1090 Clean up obsolete build option for regex
  configure.ac
  meson.build
  meson_options.txt
Labels: build

#1091 Update requirements for dependencies (gcc >= 8)
  CONTRIBUTING.md
  INSTALL
  README.md
  configure.ac
  docs/manual/make.md
  docs/manual/start.md
  meson.build
Labels: feature, document, build

#1092 Update documents to replace autotools with meson
  .github/workflows/ccpp.yml
  INSTALL
  README.md
  configure.ac
  docs/manual/environment.md
  docs/manual/make.md
  docs/manual/sound.md
  docs/manual/start.md
  meson.build
  src/main.cpp
  test/README.md
Labels: document, build

#1093 buidfix: add missing cstdint to misccharcode.cpp
  src/jdlib/misccharcode.cpp
Labels: bug

#1094 Iconv: Grow buffer size to continue iconv if output buffer is shortage
  src/jdlib/jdiconv.cpp
  src/jdlib/jdiconv.h
Labels: feature

#1095 dbtree: Get rid of buffer length limitation
  src/dbtree/nodetreejbbs.cpp
  src/dbtree/nodetreemachi.cpp
  src/jdlib/jdiconv.h
Labels: feature

#1096 Iconv: Use U+FFFD REPLACEMENT CHARACTER on converting to UTF-8
  src/jdlib/jdiconv.cpp
  src/jdlib/jdiconv.h
  test/gtest_jdlib_jdiconv.cpp
Labels: feature

#1097 Iconv: Add about:config option that wrong sjis assumes to be utf8
  src/config/aboutconfig.cpp
  src/config/configitems.cpp
  src/config/configitems.h
  src/config/defaultconf.h
  src/config/globalconf.cpp
  src/config/globalconf.h
  src/jdlib/jdiconv.cpp
  src/jdlib/jdiconv.h
  test/gtest_jdlib_jdiconv.cpp
Labels: feature

#1098 Add override keyword to virtual function declarations
  src/control/mousekeypref.h
  src/skeleton/menubutton.h
Labels: refactoring
