Repository JDimproved/JDim, pull requests merged in 2023-08, with the labels that each got.

#1215 Implement shortcut key and mouse gesture for moving to updatable tab
  docs/manual/mouse.md
  docs/manual/operation.md
  src/article/articleviewpreview.cpp
  src/control/controlid.h
  src/control/controllabel.h
  src/control/controlutil.cpp
  src/control/defaultconf.h
  src/control/keyconfig.cpp
  src/control/keypref.cpp
  src/control/mouseconfig.cpp
  src/control/mousepref.cpp
  src/image/imageadmin.cpp
  src/image/imageadmin.h
  src/message/messageadmin.cpp
  src/message/messageadmin.h
  src/message/messageviewbase.cpp
  src/skeleton/admin.cpp
  src/skeleton/admin.h
  src/skeleton/editview.cpp
Labels: feature

#1216 Add handling to use 2ch proxy if past logs not available without proxy
  src/config/configitems.cpp
  src/config/configitems.h
  src/config/defaultconf.h
  src/config/globalconf.cpp
  src/config/globalconf.h
  src/dbtree/nodetree2ch.cpp
  src/proxypref.h
Labels: feature

#1217 Socket: Define AI_V4MAPPED for OpenBSD
  src/jdlib/jdsocket.cpp
Labels: bug, build

#1221 Log_Manager::check_write: skip heading continuous newlines for early-check
  src/message/logmanager.cpp
Labels: bug

#1222 Add logic to identify `<a>` elements as reply anchors in HTML parsing
  src/dbtree/nodetreebase.cpp
Labels: bug

#1223 DrawAreaBase: Add null check to fix segfault
  src/article/drawareabase.cpp
Labels: bug

#1224 DrawAreaBase: Use cairo_t instead of std::unique_ptr<cairo_t>
  src/article/drawareabase.cpp
  src/article/drawareabase.h
Labels: bug

#1226 NodeTreeBase: Fix schema-less URL parsing
  src/dbtree/nodetreebase.cpp
Labels: bug

#1227 dbimg: Add const qualifier to pointer variables in local scope
  src/dbimg/imginterface.cpp
Labels: bug

#1230 Extend proxy support for accessing kako log server in fallback
  src/dbtree/nodetree2ch.cpp
Labels: bug, feature

#1231 Deprecate platforms where gcc version less than 9
  INSTALL
  README.md
  docs/manual/make.md
Labels: document

#1232 History_Manager: Add const qualifier to pointer variables in local scope
  src/history/historymanager.cpp
Labels: bug

#1234 BoardBase: Add const qualifier to pointer variables in local scope
  src/dbtree/boardbase.cpp
Labels: bug

#1235 skeleton: Add const qualifier to pointer variables in local scope
  src/skeleton/admin.cpp
  src/skeleton/dragnote.cpp
  src/skeleton/tabnote.cpp
Labels: bug

#1237 NodeTreeBase: Fix HTML href attribute parsing
  src/dbtree/nodetreebase.cpp
Labels: bug
