Repository JDimproved/JDim, pull requests merged in 2025-04, with the labels that each got.

#1535 Update histories
  docs/manual/2025.md
  src/jdversion.h
Labels: document

#1537 5chに時間が古いと言われてかけなくなったので、timeに現在時間を入れたとても暫定的な対応
  src/dbtree/article2ch.cpp
Labels: bug

#1539 Refactor session containers: replace std::list with std::vector for URLs and lock states
  src/article/articleadmin.cpp
  src/board/boardadmin.cpp
  src/core.cpp
  src/history/historymanager.cpp
  src/image/imageadmin.cpp
  src/image/imageadmin.h
  src/menuslots.cpp
  src/session.cpp
  src/session.h
  src/skeleton/admin.cpp
  src/skeleton/admin.h
Labels: refactoring

#1541 Fix confirmation dialog expanding to full screen width
  src/message/messageviewbase.cpp
  src/message/post.cpp
Labels: bug

#1542 Add build configuration for riscv64 snap package
  snap/snapcraft.yaml
Labels: snap
